### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by archimedix** [MikeCheng1208/vue-metamask#2]
No more compatibility with the last change:
https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8 ?

**Comment by MikeCheng1208** [comment]
@archimedix 
Thank you.
I will adjust the update in the near future.

**Comment by payammeyer** [comment]
Any idea when this would be fixed, if ever?

**Comment by MikeCheng1208** [comment]
@archimedix @payammeyer Now fixed
