### ISSUE TITLE
Module not compatible with Metamask extension version 9.0.3

### ISSUE THREAD

**Issue by Effobless2** [MikeCheng1208/vue-metamask#5]
![Capture](https://user-images.githubusercontent.com/33808798/105609589-9a54bc00-5daa-11eb-8f71-4cb224437d06.PNG)

**Comment by MikeCheng1208** [comment]
metamask remove default web3.js, I will import web3.js in vue-metamask.
Give me a little time, thx.

**Comment by BvdMerwe** [comment]
Any update on this?

**Comment by MikeCheng1208** [comment]
Hi @Effobless2 @BvdMerwe 
I have fix this issues.
Now, you can install get MetaMask information.
